name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Check Node version
        run: node --version

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        # Asegúrate de que 'npm run build' genere el directorio correcto, por ejemplo, ./build

      # Elimina o comenta este bloque que falla:
      # - name: Deploy to Netlify
      #   uses: netlify/actions/deploy@v1
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   with:
      #     publish_dir: ./build

      - name: Deploy to Netlify (Alternative)       
        uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: ./dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: List output directory
        run: ls -la
    
      - name: Notify Deployment
        run: echo "Deployment to Netlify completed successfully!"

      - name: Clean Up
        run: rm -rf node_modules

      - name: Post-Deployment Actions
        run: |
          echo "Post-deployment actions can be added here."
          
      - name: Finalize Deployment
        run: echo "Deployment process has been finalized."

      - name: Check Deployment Status
        run: |
          echo "Checking deployment status..."
          curl -X GET "https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys" \
            -H "Authorization: Bearer ${{ secrets.NETLIFY_AUTH_TOKEN }}"
          echo "Deployment status checked."

      - name: Notify Deployment Success
        run: |
          echo "Deployment to Netlify was successful!"

      - name: Final Cleanup
        run: |
          echo "Performing final cleanup..."
          rm -rf ./temp
          echo "Final cleanup completed."

      - name: Deployment Complete
        run: echo "Deployment to Netlify is complete!"

      - name: Notify Deployment Completion
        run: |
          echo "Deployment process has been completed successfully!"

      - name: Finalize Workflow
        run: echo "GitHub Actions workflow has been finalized."

      - name: Cleanup Artifacts
        run: |
          echo "Cleaning up artifacts..."
          rm -rf ./artifacts
          echo "Artifacts cleaned up."

      - name: Notify Workflow Completion
        run: |
          echo "GitHub Actions workflow has been completed successfully!"

      - name: Final Notification
        run: |
          echo "Final notification: Deployment and workflow completed successfully!"
